name: Submit a NWBEP to the Technical Advisory Board
description: NWB Enhancement Proposals will be publicly reviewed by the NWB TAB
labels: New Proposal
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for submitting an NWB Enhancement Proposal to the Technical Advisory Board!
  - type: input
    id: name
    attributes:
      label: NWBEP Title
      description: What is the NWBEP number and title? Please also use this as the Title in the textbox above.
      placeholder: "ex. NWBEP001: Events and TTL Data"
    validations:
      required: true
  - type: input
    id: nwbep_link
    attributes:
      label: Link to NWBEP
      description: Provide a link to the publicly accessible Google Doc or other doc with the NWBEP.
      placeholder: "ex. https://docs.google.com/..."
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: NWBEP Summary
      description: Copy and paste the NWBEP summary here.
    validations:
      required: true
  - type: input
    id: contact_name
    attributes:
      label: Point of Contact Name
      description: Who should we get in touch with if we need more info?
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: input
    id: contact_email
    attributes:
      label: Point of Contact Email
      description: How can we get in touch with the Point of Contact if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
